const VARIANT_ID_1 = process.env.NEXT_PUBLIC_SHOPIFY_VARIANT_ID1 || "";
const VARIANT_ID_2 = process.env.NEXT_PUBLIC_SHOPIFY_VARIANT_ID2 || "";

const PRINT_SELLING_PLAN_ID = process.env.NEXT_PUBLIC_PRINT_SELLING_PLAN_ID || "";
const DIGITAL_SELLING_PLAN_ID = process.env.NEXT_PUBLIC_DIGITAL_SELLING_PLAN_ID || "";

export { VARIANT_ID_1, VARIANT_ID_2, PRINT_SELLING_PLAN_ID, DIGITAL_SELLING_PLAN_ID };
